name: 222e to Gitee Repo

on: [push, repository_dispatch]

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source-repo: 'git@github.com:222e/222e.github.io.git'
          destination-repo: 'git@gitee.com:xsjx/xsjx.git'
