name: Myblog to Github Repo

on: push

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source-repo: 'git@gitee.com:xsjx/myblog.git'
          destination-repo: 'git@github.com:222e/myblog.git'
